spring.application.name=ApiData
server.port=8083

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbit
spring.rabbitmq.password=rabbit

logging.level.org.springframework.data.mongodb=DEBUG

spring.data.mongodb.auto-index-creation=true


